flowchart LR
  subgraph appdoc.py
    G812_0([appdoc.py])
  end
  subgraph appdoc_copy.py
    G704_0([appdoc_copy.py])
  end
  subgraph debug_output.txt
    G4_0([debug_output.txt])
  end
  subgraph IMPLEMENTATION_PLAN.md
    G550_0([IMPLEMENTATION_PLAN.md])
  end
  subgraph launch_appdocu.py
    G227_0([launch_appdocu.py])
  end
  subgraph minimal_test_import.py
    G697_0([minimal_test_import.py])
  end
  subgraph OPTIMIZATION_TASKS.md
    G218_0([OPTIMIZATION_TASKS.md])
  end
  subgraph README.md
    G274_0([README.md])
  end
  subgraph requirements.txt
    G802_0([requirements.txt])
  end
  subgraph run_docs.py
    G423_0([run_docs.py])
  end
  subgraph run_docs_tmp.py
    G562_0([run_docs_tmp.py])
  end
  subgraph simple_appdoc.py
    G628_0([simple_appdoc.py])
  end