name: AppDocU Task
about: Add new pattern cue, extend behavior edge, or other AppDocU enhancement
title: "[AppDocU Task]: "
labels: ["enhancement", "appdocu"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to AppDocU! Please fill out this form to help us understand your enhancement request.
  - type: dropdown
    id: task-type
    attributes:
      label: Task Type
      description: What type of enhancement are you requesting?
      options:
        - Add new pattern cue
        - Extend behavior edge
        - Improve confidence scoring
        - Add new template
        - Fix documentation issue
        - Add language support
        - Improve diagram generation
        - Other enhancement
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the enhancement you'd like to see
      placeholder: Provide detailed information about the enhancement...
    validations:
      required: true
 - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: What is the current behavior? (if applicable)
      placeholder: Describe the current behavior...  - type: textarea
    id: desired-behavior
    attributes:
      label: Desired Behavior
      description: What would you like to see happen?
      placeholder: Describe the desired behavior...
  - type: input
    id: language
    attributes:
      label: Language/Technology (if applicable)
      description: Which programming language or technology does this apply to?
      placeholder: e.g., Python, C#, JavaScript, React, SQL, ABAP
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Please provide code examples or scenarios where this enhancement would be useful
      placeholder: Provide code snippets, file patterns, or use cases...
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this enhancement?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
