flowchart LR
  subgraph appdoc.py
    G600_0([appdoc.py])
  end
  subgraph appdoc_copy.py
    G571_0([appdoc_copy.py])
  end
  subgraph architecture.md
    G604_0([architecture.md])
  end
  subgraph change-impact-map.md
    G981_0([change-impact-map.md])
  end
  subgraph cognitive-audit.md
    G67_0([cognitive-audit.md])
  end
  subgraph debug_output.txt
    G373_0([debug_output.txt])
  end
  subgraph developer-preflight.md
    G227_0([developer-preflight.md])
  end
  subgraph diagrams.md
    G376_0([diagrams.md])
  end
  subgraph IMPLEMENTATION_PLAN.md
    G953_0([IMPLEMENTATION_PLAN.md])
  end
  subgraph launch_appdocu.py
    G118_0([launch_appdocu.py])
  end
  subgraph logic-and-workflows.md
    G739_0([logic-and-workflows.md])
  end
  subgraph minimal_test_import.py
    G73_0([minimal_test_import.py])
  end